# Generated by Django 4.2.4 on 2023-11-08 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
