# Generated by Django 4.2.4 on 2023-09-02 12:34

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=Accounts.models.user_directory_path
            ),
        ),
    ]
