# Generated by Django 4.2.4 on 2023-09-09 07:57

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_myuser_bio_alter_myuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="photo",
            field=models.ImageField(
                default="default-profile.png",
                upload_to=Accounts.models.user_directory_path,
            ),
        ),
    ]
